export const getInitialValues = () => {
  return {
    city: '新北市',
    device: {
      airConditioner: false,
      bed: false,
      cable: true,
      chair: false,
      heater: false,
      laundryMachine: false,
      network: true,
      refrigerator: false,
      sofa: false,
      table: true,
      television: false,
      wardrobe: false,
    },
    distict: '三峽區',
    floor: 5,
    houseDetail: '無',
    livingroomAmount: 5,
    others: {
      kitchen: true,
      elevator: false,
    },
    price: 20000,
    priceInclude: {
      associationFee: false,
      cleaningFee: true,
      networkBill: false,
      waterBill: true,
    },
    require: {
      cook: '',
      deposit: '',
      gender: '',
      identify: '',
      leastPeriod: '',
      pet: '',
    },
    restroomAmount: 5,
    roomAmount: 5,
    roomType: '雅房',
    size: '12坪',
    street: '建安路',
    surrounding: '還在想',
    title: '哈哈',
    totalFloor: 5,
    latLng: {
      lat: 5,
      lng: 5,
    },
  }
}
